#-*- coding: utf-8 -*-

{
	"name": "Vit_stock_opname",
	"version": "1.0", 
	"depends": [
		'base','mrp','product'
	],
	'author': 'firmanrizaldiyusup@gmail.com',
	'website': 'http://www.vitraining.com',
	"summary": "This is the Stock opname module generated by StarUML Odoo Generator Pro Version",
	"description": """



""",
	"data": [
		"security/ir.model.access.csv",
		"view/menu.xml",
		"view/stock_opname.xml",
		"sequence/squence.xml",
  
		# "report/stock_opname.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}